### PR TITLE
Renamed all occurrances of SetLegacyState(_, Null) to RemoveLegacyState(_)

### PR DESCRIPTION
**Pull request by TheMarvelFan**
Fixes issue #2839 

The files changed are:
.Lib9c.Tests/Action/ClaimStakeRewardTest.cs
.Lib9c.Tests/Action/Garages/DeliverToOthersGaragesTest.cs
.Lib9c.Tests/Action/Garages/UnloadFromMyGaragesTest.cs
Lib9c.DevExtensions/Action/CreateOrReplaceAvatar.cs
Lib9c/Action/BuyProduct.cs
Lib9c/Action/CancelProductRegistration.cs
Lib9c/Action/EndPledge.cs
Lib9c/Action/MigrateMonsterCollection.cs
Lib9c/Action/Stake2.cs

### CODE REVIEW

**Comment by ipdae** [comment]
@moreal As far as I know, there is no distinction between null and Null.Value. https://github.com/planetarium/NineChronicles.Headless/blob/v200220/NineChronicles.Headless/BlockChainService.cs#L120-L121

**Comment by ipdae** [comment]
It seems like the changes in `BuyProduct, CancelProductRegistration` might affect the changes in https://github.com/planetarium/lib9c/pull/2789. It would be better to exclude the changes in those actions.

**Comment by TheMarvelFan** [comment]
@ipdae @moreal 

It looks like an assert is failing because it exects "Null.Value" instead of "null" in CreateOrReplaceAvatarTest.cs
Shall I modify the test to expect "null" instead of "Null.Value"?

**Comment by moreal** [comment]
> Shall I modify the test to expect "null" instead of "Null.Value"?

@TheMarvelFan I think so. You can use `Assert.Null`

**Comment by TheMarvelFan** [comment]
@moreal 
Sure. I will also need to make the same changes in some other test files such as MarketScenarioTest.cs and Stake2Test.cs.

**Comment by TheMarvelFan** [comment]
@moreal 
 I have updated the test files to Assert.Null, and all tests are passing locally.
 
Files Changed:
.Lib9c.DevExtensions.Tests/Action/CreateOrReplaceAvatarTest.cs
.Lib9c.Tests/Action/EndPledgeTest.cs
.Lib9c.Tests/Action/Scenario/MarketScenarioTest.cs
.Lib9c.Tests/Action/Stake2Test.cs

**Review by moreal — APPROVED** [review]

**Review by sonohoshi — APPROVED** [review]

**Pull request merged**
