### PR TITLE
introduce mysql migration tool

### LINKED ISSUE #349: Create db migration tool from RocksDB to MySQL
Currently, adding data to MySQL from Block 0 takes too long (over 1M blocks at this point). Therefore, a migration tool is needed to move pre-existing RocksDB data to MySQL.

### PR DESCRIPTION
**Pull request by area363**
This PR resolves #349.

### CODE REVIEW

**Review by moreal — COMMENTED** [review]
@area363 I wonder why planetarium/lib9c should have *MySQL* migration tool. There is no features related with *MySQL* and also in planetarium/libplanet. It seems related with `MySQLStore` in *planetarium/libplanet-explorer* when we see some methods like `StoreTxReferences`.

**Comment by area363** [comment]
> @area363 I wonder why planetarium/lib9c should have _MySQL_ migration tool. There is no features related with _MySQL_ and also in planetarium/libplanet. It seems related with `MySQLStore` in _planetarium/libplanet-explorer_ when we see some methods like `StoreTxReferences`.

@moreal I see, that makes sense. Would a separate directory within `planetarium/libplanet-explorer` like `Libplanet.Explorer.Tools` be a more suitable location for this migration tool?

**Comment by moreal** [comment]
> @moreal I see, that makes sense. Would a separate directory within `planetarium/libplanet-explorer` like `Libplanet.Explorer.Tools` be a more suitable location for this migration tool?

IMO **yes**.

**Comment by area363** [comment]
> > @moreal I see, that makes sense. Would a separate directory within `planetarium/libplanet-explorer` like `Libplanet.Explorer.Tools` be a more suitable location for this migration tool?
> 
> IMO **yes**.

Great! I'll make rearrangements and submit a new PR. 🙇

**Comment by area363** [comment]
Closing this PR because it is replaced by https://github.com/planetarium/libplanet-explorer/pull/178.

**Pull request closed without merging**
