### PR TITLE
PR for Action Base Class changes

### PR DESCRIPTION
**Pull request by umardevX**

### CODE REVIEW

**Comment by moreal** [comment]
Hello @umardevX, could you organize the commits included in the PR? I think it only needs one commit.

**Comment by umardevX** [comment]
@moreal I'm unable to remove extra first & reverted commit while generating PR they automatically pick all three commits.
Also i accepted the CLA but i don't know why it is blocked

**Comment by moreal** [comment]
@umardevX 

> Also i accepted the CLA but i don't know why it is blocked

Oh I see your agreement. It may be a problem of CLA application. ✅ 

> I'm unable to remove extra first & reverted commit while generating PR they automatically pick all three commits.

Yeah, you cannot remove them in GitHub UI. you should use `git` command. You can search about `git rebase -i` command to remove commits. Or you can reset your branch and cherry-pick the last commit (`git-reset`, `git-cherry-pick` commands).

If you research the way with the keywords, but it is too hard to know how to remove them, ask me again!

**Comment by moreal** [comment]
@umardevX I didn't read the CLA comment as well 😥 It says the answer:

> Umar Farooq seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

Screenshot 2024-10-17 at 8 57 58 PM

You have to setup your email to your commits. In your case, you can see [this GitHub docs](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address#setting-your-email-address-for-every-repository-on-your-computer)

**Comment by umardevX** [comment]
@moreal  I tried to remove commits from git history but still it appears in vs git history unable to delete that all previous commits. Should i make again a single one final commit with changes and commit with CLA connected email?

**Comment by moreal** [comment]
> I tried to remove commits from git history but still it appears in vs git history unable to delete that all previous commits. Should i make again a single one final commit with changes and commit with CLA connected email?

Yes. Are you unfamiliar with Git CLI?

**Comment by umardevX** [comment]
@moreal I'm not expert but i have the intermediate knowledge. I'm using git rebate but not working successfully.

**Pull request closed without merging**
