### PR TITLE
feat: implement `Addresses.GetAccountAddress(currency)` method

### PR DESCRIPTION
**Pull request by boscohyun**
SSIA

### CODE REVIEW

**Review by moreal — COMMENTED** [review]
What is the expected use case in Lib9c project for the new method?

**Comment by boscohyun** [comment]
> What is the expected use case in Lib9c project for the new method?

I was expecting it to be used by those using `Lib9c`, and thought it would be easier to simply provide the account address for the call.

**Comment by moreal** [comment]
> I was expecting it to be used by those using `Lib9c`, and thought it would be easier to simply provide the account address for the call.

I understand your intention, but I was wondering who exactly will be using the API. In another thought, I think it should be provided by the "Libplanet" library. How about suggesting this to them?

**Comment by boscohyun** [comment]
> I think it should be provided by the "Libplanet" library. How about suggesting this to them?

I agree. Hmm.. I'll request this to libplanet.👍

**Comment by boscohyun** [comment]
Replace with this issue:
https://github.com/planetarium/libplanet/issues/3987

**Pull request closed without merging**
