### PR TITLE
Remove unused actions

### PR DESCRIPTION
**Pull request by moreal**
This pull request removes unused actions:

 - `transfer_asset`
 - `stake`
 - `activate_account2`
 - `add_activated_account2`

### CODE REVIEW

**Comment by ipdae** [comment]
Could you please check if there will be any issues when this pull request is applied on  https://github.com/planetarium/NineChronicles.DataProvider ?

**Comment by moreal** [comment]
> Could you please check if there will be any issues when this pull request is applied on [planetarium/NineChronicles.DataProvider](https://github.com/planetarium/NineChronicles.DataProvider) ?

Okay, I'll leave a comment after checking it.

**Comment by moreal** [comment]
@ipdae I tried to bump lib9c submodule in NineChronicles.Headless submodule.

Along the way, we also encountered a crash in NineChronicles.Headless, but it was related to a GraphQL query. I think it's okay to lose fields related to action queries or activation.

I get two errors when handling it on the DataProvider side. They come from Stake0 and TransferAsset0. However, both actions have Stake and TransferAsset action handlers, so I think it's fine. As long as you don't follow them from very far back in the block.

**Comment by ipdae** [comment]
@moreal So, are you going to fix the errors caused by this change?

**Comment by moreal** [comment]
> @moreal So, are you going to fix the errors caused by this change?

@ipdae Yes. Then I'll open two pull requests to `NineChronicles.Headless` development and `NineChronicles.DataProvider` development as draft state, and I'll let you know.

**Review by ipdae — APPROVED** [review]

**Review by U-lis — APPROVED** [review]

**Comment by U-lis** [comment]
@moreal  Any updates?
Please update base branch (development) and check it is still mergeable.

**Comment by moreal** [comment]
@U-lis Thanks to check this pull request. But I don't have time to do what follows. So I'll turn this pull request to draft state and you can ignore this pull request until this pull request reopend.

**Comment by moreal** [comment]
After https://github.com/planetarium/NineChronicles.Headless/pull/2540 PR merged, I'll merge this pull request and bump to headless and other projects.

**Pull request merged**
