### PR TITLE
🧹 Cleanup rehearsal related code.

### PR DESCRIPTION
**Pull request by greymistcube**
After #2221, there is no proper code path which would allow `IActionContext.Rehearsal` to be `true`.

### CODE REVIEW

**Comment by riemannulus** [comment]
Is it tested on the mainnet?

**Comment by greymistcube** [comment]
Eh, sure why not. I'll test it and report back. 😶

**Comment by greymistcube** [comment]
@riemannulus 
Currently being tested on mainnet. Seems to be working fine so far. 😗

**Review by riemannulus — APPROVED** [review]
LGTM

**Pull request merged**
